service: ecopay # サービス名

image: keitatawara/ecopay # Dockerのアカウント名/サービス名

servers:
  web:
    hosts:
      - 54.250.238.33 # パブリック IP アドレス
    cmd: ./bin/rails server
    env:
      secret:
        - KAMAL_REGISTRY_PASSWORD
        - RAILS_MASTER_KEY

proxy:
  ssl: true
  host: ecopay.kei-apps.com # ドメイン名
  app_port: 3000

registry:
  username: keitatawara # Dockerのアカウント名
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: ec2-user
  keys: ["~/.ssh/ecoPay.pem"]

volumes:
- "app_storage:/rails/storage"
- "db:/rails/db"
